server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3333/dgsw_26_1st_01
    username: root
    password: dgsw.hs.kr
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true